module.exports = {

  interaction: {
    enabledMethods: [
      'create',
      // 'patchOrCreate',
      // 'replaceOrCreate',
      // 'upsertWithWhere',
      'exists',
      'findById',
      'replaceById',
      // 'find',
      // 'findOne',
      // 'updateAll',
      'deleteById',
      // 'count',
      'patchAttributes',
      // 'createChangeStream',

      'prototype.patchAttributes',

      'prototype.__findById__job',
      'prototype.__destroyById__job',
      'prototype.__updateById__job',
      'prototype.__exists__job',
      'prototype.__link__job',
      'prototype.__get__job',
      'prototype.__create__job',
      'prototype.__update__job',
      'prototype.__destroy__job',
      'prototype.__unlink__job',
      'prototype.__count__job',
      'prototype.__delete__job',

      'prototype.__findById__user',
      'prototype.__destroyById__user',
      'prototype.__updateById__user',
      'prototype.__exists__user',
      'prototype.__link__user',
      'prototype.__get__user',
      'prototype.__create__user',
      'prototype.__update__user',
      'prototype.__destroy__user',
      'prototype.__unlink__user',
      'prototype.__count__user',
      'prototype.__delete__user',
    ],
  },

  job: {
    enabledMethods: [
      'create',
      // 'patchOrCreate',
      // 'replaceOrCreate',
      // 'upsertWithWhere',
      'exists',
      'findById',
      'replaceById',
      // 'find',
      // 'findOne',
      // 'updateAll',
      'deleteById',
      // 'count',
      'patchAttributes',
      // 'createChangeStream',

      'prototype.patchAttributes',

      'prototype.__findById__search',
      'prototype.__destroyById__search',
      'prototype.__updateById__search',
      'prototype.__exists__search',
      'prototype.__link__search',
      'prototype.__get__search',
      'prototype.__create__search',
      'prototype.__update__search',
      'prototype.__destroy__search',
      'prototype.__unlink__search',
      'prototype.__count__search',
      'prototype.__delete__search',

      // 'prototype.__findById__interactions',
      // 'prototype.__destroyById__interactions',
      // 'prototype.__updateById__interactions',
      'prototype.__exists__interactions',
      'prototype.__link__interactions',
      'prototype.__get__interactions',
      // 'prototype.__create__interactions',
      'prototype.__update__interactions',
      'prototype.__destroy__interactions',
      'prototype.__unlink__interactions',
      'prototype.__count__interactions',
      // 'prototype.__delete__interactions',

      // 'prototype.__findById__offers',
      // 'prototype.__destroyById__offers',
      // 'prototype.__updateById__offers',
      'prototype.__exists__offers',
      'prototype.__link__offers',
      'prototype.__get__offers',
      // 'prototype.__create__offers',
      'prototype.__update__offers',
      'prototype.__destroy__offers',
      'prototype.__unlink__offers',
      'prototype.__count__offers',
      // 'prototype.__delete__offers',

      'prototype.__findById__user',
      'prototype.__destroyById__user',
      'prototype.__updateById__user',
      'prototype.__exists__user',
      'prototype.__link__user',
      'prototype.__get__user',
      'prototype.__create__user',
      'prototype.__update__user',
      'prototype.__destroy__user',
      'prototype.__unlink__user',
      'prototype.__count__user',
      'prototype.__delete__user',
    ],
  },

  offer: {
    enabledMethods: [
      'create',
      // 'patchOrCreate',
      // 'replaceOrCreate',
      // 'upsertWithWhere',
      'exists',
      'findById',
      'replaceById',
      // 'find',
      // 'findOne',
      // 'updateAll',
      'deleteById',
      // 'count',
      'patchAttributes',
      // 'createChangeStream',

      'prototype.patchAttributes',

      'prototype.__findById__job',
      'prototype.__destroyById__job',
      'prototype.__updateById__job',
      'prototype.__exists__job',
      'prototype.__link__job',
      'prototype.__get__job',
      'prototype.__create__job',
      'prototype.__update__job',
      'prototype.__destroy__job',
      'prototype.__unlink__job',
      'prototype.__count__job',
      'prototype.__delete__job',

      'prototype.__findById__user',
      'prototype.__destroyById__user',
      'prototype.__updateById__user',
      'prototype.__exists__user',
      'prototype.__link__user',
      'prototype.__get__user',
      'prototype.__create__user',
      'prototype.__update__user',
      'prototype.__destroy__user',
      'prototype.__unlink__user',
      'prototype.__count__user',
      'prototype.__delete__user',
    ],
  },


  search: {
    enabledMethods: [
      'create',
      // 'patchOrCreate',
      // 'replaceOrCreate',
      // 'upsertWithWhere',
      'exists',
      'findById',
      'replaceById',
      // 'find',
      // 'findOne',
      // 'updateAll',
      'deleteById',
      // 'count',
      'patchAttributes',
      // 'createChangeStream',

      'prototype.patchAttributes',

      // 'prototype.__findById__jobs',
      // 'prototype.__destroyById__jobs',
      // 'prototype.__updateById__jobs',
      'prototype.__exists__jobs',
      'prototype.__link__jobs',
      'prototype.__get__jobs',
      // 'prototype.__create__jobs',
      'prototype.__update__jobs',
      'prototype.__destroy__jobs',
      'prototype.__unlink__jobs',
      'prototype.__count__jobs',
      // 'prototype.__delete__jobs',

      'prototype.__findById__user',
      'prototype.__destroyById__user',
      'prototype.__updateById__user',
      'prototype.__exists__user',
      'prototype.__link__user',
      'prototype.__get__user',
      'prototype.__create__user',
      'prototype.__update__user',
      'prototype.__destroy__user',
      'prototype.__unlink__user',
      'prototype.__count__user',
      'prototype.__delete__user',
    ],
  },


  user: {
    enabledMethods: [
      'create',
      // 'patchOrCreate',
      // 'replaceOrCreate',
      // 'upsertWithWhere',
      'exists',
      'findById',
      'replaceById',
      // 'find',
      // 'findOne',
      // 'updateAll',
      'deleteById',
      // 'count',
      'patchAttributes',
      // 'createChangeStream',

      'login',
      'logout',
      'confirm',
      'resetPassword',

      'prototype.patchAttributes',

      // 'prototype.__destroyById__accessTokens',
      // 'prototype.__updateById__accessTokens',
      'prototype.__exists__accessTokens',
      'prototype.__link__accessTokens',
      'prototype.__get__accessTokens',
      // 'prototype.__create__accessTokens',
      'prototype.__update__accessTokens',
      'prototype.__destroy__accessTokens',
      'prototype.__unlink__accessTokens',
      'prototype.__count__accessTokens',
      // 'prototype.__delete__accessTokens',

      // 'prototype.__findById__interactions',
      // 'prototype.__destroyById__interactions',
      // 'prototype.__updateById__interactions',
      'prototype.__exists__interactions',
      'prototype.__link__interactions',
      'prototype.__get__interactions',
      // 'prototype.__create__interactions',
      'prototype.__update__interactions',
      'prototype.__destroy__interactions',
      'prototype.__unlink__interactions',
      'prototype.__count__interactions',
      // 'prototype.__delete__interactions',

      // 'prototype.__findById__jobs',
      // 'prototype.__destroyById__jobs',
      // 'prototype.__updateById__jobs',
      'prototype.__exists__jobs',
      'prototype.__link__jobs',
      'prototype.__get__jobs',
      // 'prototype.__create__jobs',
      'prototype.__update__jobs',
      'prototype.__destroy__jobs',
      'prototype.__unlink__jobs',
      'prototype.__count__jobs',
      // 'prototype.__delete__jobs',

      // 'prototype.__findById__offers',
      // 'prototype.__destroyById__offers',
      // 'prototype.__updateById__offers',
      'prototype.__exists__offers',
      'prototype.__link__offers',
      'prototype.__get__offers',
      // 'prototype.__create__offers',
      'prototype.__update__offers',
      'prototype.__destroy__offers',
      'prototype.__unlink__offers',
      'prototype.__count__offers',
      // 'prototype.__delete__offers',

      // 'prototype.__findById__searches',
      // 'prototype.__destroyById__searches',
      // 'prototype.__updateById__searches',
      'prototype.__exists__searches',
      'prototype.__link__searches',
      'prototype.__get__searches',
      // 'prototype.__create__searches',
      'prototype.__update__searches',
      'prototype.__destroy__searches',
      'prototype.__unlink__searches',
      'prototype.__count__searches',
      // 'prototype.__delete__searches',
    ],
  },
};
